# Schema for the configuration files of the Ai content validation module.
ai_content_validation.settings:
  type: config_object
  label: 'Ai content validation settings'
  mapping:
    flows:
      label: 'flows'
      sequence:
        type: string
